# Development environment override
services:
  tera-database:
    ports:
      - '22432:5432/tcp'
    networks:
      - lychen-network

  tera-api:
    build:
      context: .
      target: frankenphp_dev
    environment:
      SERVER_NAME: api.tera.lychen.local
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
    volumes:
      - ./:/app
      #- ./var:/app/var
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    ports:
      - protocol: tcp
        published: ${HTTP_PORT:-8081}
        target: 80
      - protocol: tcp
        published: ${HTTPS_PORT:-31443}
        target: 443
      - protocol: udp
        published: ${HTTP3_PORT:-41443}
        target: 443
    networks:
      - lychen-network

  tera-redis:
    networks:
      - lychen-network

  tera-rabbitmq:
    networks:
      - lychen-network

networks:
  lychen-network:
    external: true
