services:
  database:
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-PasswordForLocal!}
      - POSTGRES_USER=${POSTGRES_USER:-userlocal}
    healthcheck:
      retries: 5
      start_period: 60s
      test: [ 'CMD', 'pg_isready', '-d', '${POSTGRES_DB:-app}', '-U', '${POSTGRES_USER:-userlocal}' ]
      timeout: 5s
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  api:
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    environment:
      APP_RUNTIME: Runtime\FrankenPhpSymfony\Runtime
      DATABASE_URL: postgresql://${POSTGRES_USER:-userlocal}:${POSTGRES_PASSWORD:-PasswordForLocal!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
      MESSENGER_TRANSPORT_DSN: amqp://app:app@rabbitmq:5672/app
      REDIS_URL: redis://redis:6379
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
    image: ${IMAGES_PREFIX:-}tera-api:${IMAGE_TAG:-latest}
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ../../../libs/php:/packages

  redis:
    healthcheck:
      retries: 5
      start_period: 10s
      test: [ 'CMD', 'redis-cli', 'ping' ]
      timeout: 3s
    image: redis:alpine
    volumes:
      - redis_data:/data

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=app
      - RABBITMQ_DEFAULT_PASS=app
      - RABBITMQ_DEFAULT_VHOST=app
    healthcheck:
      retries: 5
      start_period: 30s
      test: [ 'CMD', 'rabbitmq-diagnostics', '-q', 'ping' ]
      timeout: 10s
    image: rabbitmq:4.0.4-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  caddy_config:
  caddy_data:
  database_data:
  rabbitmq_data:
  redis_data:
