services:
  api:
    image: ghcr.io/lychen-lab/lychen/production/espace/api:latest
    env_file:
      - .env
    ports:
      - 80
    restart: unless-stopped
    volumes:
      - 'caddy_data:/data'
      - 'caddy_config:/config'
      - 'api_logs:/app/var/log'

volumes:
  caddy_config:
  caddy_data:
  api_logs:
