$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  cloudflare-provision:
    options:
      cache: false
      inferInputs: false
    script: bash $workspaceRoot/.moon/scripts/cloudflare-provision.sh
  dokploy-provision:
    env:
      COMPOSE_ID_FILE: $projectRoot/.dokploy-compose-id
    options:
      cache: false
      inferInputs: false
    script: bash $workspaceRoot/.moon/scripts/dokploy-provision.sh
  dokploy-compose-deploy:
    command: bash $workspaceRoot/.moon/scripts/dokploy-compose-deploy.sh
    deps:
    - cloudflare-provision
    - dokploy-provision
    env:
      COMPOSE_ID_FILE: $projectRoot/.dokploy-compose-id
    options:
      inferInputs: false
inheritedBy:
  tag: dokploy
