$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  docker-buildx:
    command: docker buildx build $projectRoot --platform linux/arm64,linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${IMAGE_NAME}:latest --tag ${IMAGE_NAME}:${GITHUB_SHA} --tag ${IMAGE_NAME}:latest --push
    deps:
      - build
    env:
      IMAGE_NAME: ghcr.io/lychen-lab/lychen/$project
    options:
      cache: false