$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  build:
    command: yarn build
    deps:
      - args: $projectRoot/.nginx-build
        target: nginx-configs:sync-ssg
    env:
      VITE_UNHEAD_HOST: ${HOST}
    options:
      cache: false
  
  dev:
    command: yarn dev
    env:
      VITE_APP_ID: $project
      VITE_UNHEAD_HOST: ${HOST}
    options:
      persistent: true