$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  dokploy-compose-deploy:
    command: bash $workspaceRoot/.moon/scripts/dokploy-compose-deploy.sh
    deps:
      - dokploy-compose-update
    options:
      inferInputs: false

  dokploy-compose-update:
    env:
      COMPOSE_FILE: $projectRoot/compose.yml
    options:
      cache: false
    script: bash $workspaceRoot/.moon/scripts/dokploy-compose-update-from-file.sh
