$schema: https://moonrepo.dev/schemas/tasks.json
inheritedBy:
  tag: symfony
tasks:
  ci-check-vulnerabilities:
    command: docker compose -p $project -f compose.yml run --rm api ./local-php-security-checker
  ci-copy-packages:
    script: cp -R $workspaceRoot/libs/php $projectRoot/packages && find $projectRoot/packages -name "moon.yml" -type f -delete
  ci-create-db:
    command: docker compose -p $project -f compose.yml run --rm api bin/console doctrine:database:create -n --if-not-exists
  ci-export-openapi:
    command: docker compose -p $project -f compose.yml run --rm api bin/console api:openapi:export --spec-version=3.0.0 --output=openapi_docs.json
  ci-install-tools:
    command: docker compose -p $project -f compose.yml run --rm api composer install --no-interaction --working-dir=tools/
  ci-php-cs-fixer-src:
    command: docker compose -p $project -f compose.yml run --rm api tools/vendor/bin/php-cs-fixer fix src/ --rules=@Symfony --dry-run --diff
  ci-php-cs-fixer-test:
    command: docker compose -p $project -f compose.yml run --rm api tools/vendor/bin/php-cs-fixer fix tests/ --rules=@Symfony --dry-run --diff
  ci-phpstan:
    command: docker compose -p $project -f compose.yml run --rm api tools/vendor/bin/phpstan analyse --memory-limit=-1
  ci-test-build-docker-image:
    command: docker build $projectRoot --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${TEST_IMAGE_NAME}:latest --tag ${TEST_IMAGE_NAME}:${GITHUB_SHA} --tag ${TEST_IMAGE_NAME}:latest --target frankenphp_test
    deps:
      - ci-copy-packages
  ci-test-phpunit:
    command: docker compose -p $project -f compose.yml run --rm api php -d memory_limit=-1 ./vendor/bin/phpunit
  ci-update-db:
    command: docker compose -p $project -f compose.yml run --rm api bin/console doctrine:schema:update --force
  ci-validate-db-schema:
    command: docker compose -p $project -f compose.yml run --rm api bin/console doctrine:schema:validate -n
  dev:
    command: docker compose -p $project up -d
    deps:
      - common-mailpit:up
  docker-buildx:
    command: docker buildx build $projectRoot --cache-from ${IMAGE_NAME}:latest --platform linux/arm64,linux/amd64 --target frankenphp_prod -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${GITHUB_SHA} --push
    deps:
      - ci-copy-packages
    env:
      IMAGE_NAME: ghcr.io/lychen-lab/lychen/$project
    options:
      cache: false
  export-openapi:
    command: docker compose -p $project run --rm api bin/console api:openapi:export --spec-version=3.0.0 --output=openapi_docs.json
  load-fixtures:
    command: docker compose -p $project run --rm api bin/console do:fi:lo -n
  test-phpunit:
    command: docker compose -p $project run --rm api php -d memory_limit=-1 ./vendor/bin/phpunit
