$schema: https://moonrepo.dev/schemas/tasks.json
inheritedBy:
  tag: compose
tasks:
  down:
    command: docker compose -p $project down
  up:
    command: docker compose -p $project up -d
    deps:
    - common-network:create-network
