$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  build:
    command: yarn build
    deps:
      - args: $projectRoot/.nginx-build
        target: nginx-configs:sync-pwa
    env:
      VITE_APP_ID: $project
    options:
      cache: false

  dev:
    command: yarn dev
    env:
      VITE_APP_ID: $project
    options:
      persistent: true

  generate-pwa-assets:
    command: yarn generate-pwa-assets
    deps:
      - assets-sync