$schema: https://moonrepo.dev/schemas/tasks.json
inheritedBy:
  tag: dokploy
tasks:
  dokploy-compose-deploy:
    command: bash $workspaceRoot/.moon/scripts/dokploy-compose-deploy.sh
    options:
      inferInputs: false
