$schema: https://moonrepo.dev/schemas/tasks.json
inheritedBy:
  tag: ssg
tasks:
  build:
    command: yarn build
    deps:
    - args:
      - $projectRoot/.nginx-build
      target: nginx-configs:sync-ssg
    inputs:
    - .env*
    - index.html
    - package.json
    - public/**/*
    - src/**/*
    - tsconfig.json
    - vite.config.ts
    - /libs/css/**/*
    - /libs/drawio/**/*
    - /libs/i18n/**/*
    - /libs/typescript/**/*
    - /libs/vite/**/*
    - /libs/vue/**/*
    - /yarn.lock
    - project://^
    - $APP_ID
    - $ESPACE_WEBSITE_HOST
    - $HOST
    - $VITE_*
    outputs:
    - dist
  dev:
    command: yarn dev
    env:
      VITE_APP_ID: $project
      VITE_UNHEAD_HOST: ${HOST}
    options:
      persistent: true
