name: 'Frontend | Tests'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Install proto tools
        run: proto install

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: moon ci :test
