name: 'Test composite action | STACK-frontend LAYER-application'

env:
  REGISTRY: ghcr.io

on:
  pull_request:

jobs:
  define-matrix:
    name: 'Gather affected projects'
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.gather-projects.outputs.projects }}
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
        
      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - id: gather-projects
        uses: ./.github/actions/moon-affected-projects-list
        with:
          layer: 'application'
          stack: 'frontend'