name: TypeScript | Code formatting

on:
  #pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkformat:
    name: 'Check ESLint and Prettier rules'
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'
      - name: Run Prettier
        run: moon ci :format
      - name: Run ESLint
        run: moon ci :lint
